### ISSUE TITLE
Checklist - link dump

### ISSUE THREAD

**Issue by nmay231** [markerikson/redux-ecosystem-links#104]
This issue is a collection of all the links from the previous link dumps, but listed as a checklist so they can be done a little at a time.

Let me know what you think of this idea @markerikson 

**Repos to organize**

- [ ] 9technology/redux-optimal ::: https://github.com/9technology/redux-optimal
- [ ] AaronFriel/reductser ::: https://github.com/AaronFriel/reductser
- [ ] abahmed/Deer ::: https://github.com/abahmed/Deer/tree/master
- [ ] ahdinosaur/redux-state-reactor ::: https://github.com/ahdinosaur/redux-state-reactor
- [ ] airplane-mode/stage-director ::: https://github.com/airplane-mode/stage-director
- [ ] alessioscalici/redux-router ::: https://github.com/alessioscalici/redux-router
- [ ] algolia/redux-magic-async-middleware ::: https://github.com/algolia/redux-magic-async-middleware
- [ ] algolia/redux-updeep ::: https://github.com/algolia/redux-updeep
- [ ] andyjessop/redux-dynamic-registry ::: https://github.com/andyjessop/redux-dynamic-registry
- [ ] Atomic-Reactor/redux-local-persist ::: https://github.com/Atomic-Reactor/redux-local-persist
- [ ] b2io/redux-disbatch ::: https://github.com/b2io/redux-disbatch
- [ ] baublet/redux-tools ::: https://github.com/baublet/redux-tools
- [ ] BerkeleyTrue/redux-vertical ::: https://github.com/BerkeleyTrue/redux-vertical
- [ ] blueish9/redux-atom ::: https://github.com/blueish9/redux-atom
- [ ] boweihan/redux-hypercube ::: https://github.com/boweihan/redux-hypercube
- [ ] brigonzalez/redux-modular-fetch-middleware ::: https://github.com/brigonzalez/redux-modular-fetch-middleware
- [ ] callmedadaxin/easy-redux ::: https://github.com/callmedadaxin/easy-redux
- [ ] callmedadaxin/react-fetch-middleware ::: https://github.com/callmedadaxin/react-fetch-middleware
- [ ] cjies/redux-duck-immer ::: https://github.com/cjies/redux-duck-immer
- [ ] cloudflare/redux-grim ::: https://github.com/cloudflare/redux-grim
- [ ] dat2/redux-saga-fetch ::: https://github.com/dat2/redux-saga-fetch
- [ ] devx-agency/redux-persist-check-version-transform ::: https://github.com/devx-agency/redux-persist-check-version-transform
- [ ] dortzur/denormalize-selector ::: https://github.com/dortzur/denormalize-selector
- [ ] dortzur/renorm ::: https://github.com/dortzur/renorm
- [ ] EdStudio/redux-orchestrate ::: https://github.com/EdStudio/redux-orchestrate
- [ ] ferdaber/redux-observer-component ::: https://github.com/ferdaber/redux-observer-component
- [ ] fkling/astexplorer ::: https://github.com/fkling/astexplorer
- [ ] folio-sec/redux-spork ::: https://github.com/folio-sec/redux-spork
- [ ] francisrstokes/Redux-State-Resolver ::: https://github.com/francisrstokes/Redux-State-Resolver
- [ ] gitpoint/git-point ::: https://github.com/gitpoint/git-point
- [ ] go-aos/redux-hmr-registry ::: https://github.com/go-aos/redux-hmr-registry
- [ ] go-aos/xstate-redux ::: https://github.com/go-aos/xstate-redux
- [ ] gregnb/redux-axios-middleware ::: https://github.com/gregnb/redux-axios-middleware
- [ ] hex13/feedbacks ::: https://github.com/hex13/feedbacks
- [ ] hugozap/redux-p2p-middleware ::: https://github.com/hugozap/redux-p2p-middleware
- [ ] hvolschenk/payload-action-creator ::: https://github.com/hvolschenk/payload-action-creator
- [ ] Introvertuous/redux-undone ::: https://github.com/Introvertuous/redux-undone
- [ ] jacobbuck/redux-saga-uniq ::: https://github.com/jacobbuck/redux-saga-uniq
- [ ] javierfernandes/artemisajs ::: https://github.com/javierfernandes/artemisajs
- [ ] jconsigliere/redux-cancan ::: https://github.com/jconsigliere/redux-cancan
- [ ] jculloty/redux-reducer-selectors ::: https://github.com/jculloty/redux-reducer-selectors
- [ ] kouhin/redyna ::: https://github.com/kouhin/redyna
- [ ] Lapixx/enzyme-redux-helpers ::: https://github.com/Lapixx/enzyme-redux-helpers
- [ ] Lizhooh/redux-store-init ::: https://github.com/Lizhooh/redux-store-init
- [ ] makerstreet-public/redux-helpers ::: https://gitlab.com/makerstreet-public/redux-helpers
- [ ] mapbox/mapbox-gl-redux ::: https://github.com/mapbox/mapbox-gl-redux
- [ ] Microsoft/redux-dynamic-modules ::: https://github.com/Microsoft/redux-dynamic-modules
- [ ] mirakl/redux-lists ::: https://github.com/mirakl/redux-lists
- [ ] mizchi/hard-reducer ::: https://github.com/mizchi/hard-reducer
- [ ] mohanrajoria/redux-async-connector ::: https://github.com/mohanrajoria/redux-async-connector
- [ ] neoverse/spunky ::: https://github.com/neoverse/spunky
- [ ] neurosnap/robodux ::: https://github.com/neurosnap/robodux
- [ ] nschurmann/ducks-maker ::: https://github.com/nschurmann/ducks-maker
- [ ] Oblosys/react-lifecycle-visualizer ::: https://github.com/Oblosys/react-lifecycle-visualizer
- [ ] oleksiibilous/redux-query ::: https://github.com/oleksiibilous/redux-query
- [ ] outofthisworld/reduxdecorator ::: https://github.com/outofthisworld/reduxdecorator
- [ ] palantir/redoodle ::: https://github.com/palantir/redoodle
- [ ] Patreon/nion ::: https://github.com/Patreon/nion
- [ ] reduxigen/Reduxigen ::: https://github.com/reduxigen/Reduxigen
- [ ] rjdestigter/react-redux-reggae ::: https://github.com/rjdestigter/react-redux-reggae
- [ ] robertsonmcclure/redux-obtain ::: https://github.com/robertsonmcclure/redux-obtain
- [ ] RobusGauli/js-immutable ::: https://github.com/RobusGauli/js-immutable
- [ ] ryansukale/incrudable ::: https://github.com/ryansukale/incrudable
- [ ] samuelmaddock/metastream ::: https://github.com/samuelmaddock/metastream
- [ ] StephenHaney/redux-time-travel ::: https://github.com/StephenHaney/redux-time-travel
- [ ] sudo-reboot/react-redux-modules ::: https://github.com/sudo-reboot/react-redux-modules
- [ ] teamleadercrm/ddd-action-string ::: https://github.com/teamleadercrm/ddd-action-string
- [ ] technology-ebay-de/modular-toolkit ::: https://github.com/technology-ebay-de/modular-toolkit
- [ ] VariableVasasMT/create-redux-routines ::: https://github.com/VariableVasasMT/create-redux-routines
- [ ] vinpac/redux-handy ::: https://github.com/vinpac/redux-handy
- [ ] wayrunner/redux-action-creator ::: https://github.com/wayrunner/redux-action-creator
- [ ] wix/redux-cornell ::: https://github.com/wix/redux-cornell
- [ ] xnimorz/signal-middleware ::: https://github.com/xnimorz/signal-middleware
- [ ] zetsin/redux-thunk-it ::: https://github.com/zetsin/redux-thunk-it
- [ ] zewish/redux-remember ::: https://github.com/zewish/redux-remember
- [ ] zhDmitry/restate ::: https://github.com/zhDmitry/restate
- [ ] ziolko/redux-play ::: https://github.com/ziolko/redux-play

**Articles, Misc**

- [ ] expect-redux: better interaction tests with redux ::: https://ymmv.craftswerk.io/2018/11/expect-redux-better-interaction-tests-with-redux
- [ ] Getting Started ::: https://fusionjs.com/docs/overview
- [ ] GraphQL, REST, RPC, Who Cares? Keep a Single Redux Store with Iguazu ::: https://americanexpress.io/graphql-rest-who-cares-redux-iguazu/
- [ ] Home ::: https://sphinx-con.org/home
- [ ] Introducing Fusion.js: A Plugin-based Universal Web Framework ::: https://eng.uber.com/fusionjs/
- [ ] Redux Enterprise - Library for scaling development on Redux-based projects ::: https://www.reddit.com/r/reactjs/comments/94b2jc/redux_enterprise_library_for_scaling_development/
- [ ] Redux Dynamic Modules ::: https://microsoft.github.io/redux-dynamic-modules/#/
- [ ] Redux State Branch: A redux wrapper for sane people ::: https://jamesmfriedman.github.io/redux-state-branch/
- [ ] Reduxful: Manage RESTful data with Redux ::: https://godaddy.github.io/2018/11/05/reduxful-manage-restful-data-with-redux/
- [ ] The Secret to Using Redux: createNamespaceReducer ::: https://medium.com/@Sawtaytoes/the-secret-to-using-redux-createnamespacereducer-d3fed2ccca4a

**Added/Already in the system**

- [x] ~AgentME/redux-action-log ::: https://github.com/AgentME/redux-action-log~
- [x] ~goncy/async-action-creator ::: https://github.com/goncy/async-action-creator~
- [x] ~ImmoweltGroup/jest-react-redux ::: https://github.com/ImmoweltGroup/jest-react-redux~
- [x] ~jasonmorita/react-redux-ui-state ::: https://github.com/jasonmorita/react-redux-ui-state~
- [x] ~jedwards1211/redux-track-promise ::: https://github.com/jedwards1211/redux-track-promise~
- [x] ~khanghoang/redux-ittt ::: https://github.com/khanghoang/redux-ittt~
- [x] ~machadogj/redux-thunk-actions ::: https://github.com/machadogj/redux-thunk-actions~
- [x] ~myaskevich/react-redux-modal-provider ::: https://github.com/myaskevich/react-redux-modal-provider~
- [x] ~nicholasrq/redux-processor ::: https://github.com/nicholasrq/redux-processor~
- [x] ~nicholasrq/redux-processor ::: https://github.com/nicholasrq/redux-processor~
- [x] ~Qlean/redux-struct ::: https://github.com/Qlean/redux-struct~
- [x] ~quandhz/resaga ::: https://github.com/quandhz/resaga~
- [x] ~rmdm/redux-combiner ::: https://github.com/rmdm/redux-combiner~
- [x] ~sugarshin/redux-online-status ::: https://github.com/sugarshin/redux-online-status~
- [x] ~Wildhoney/Redecorate ::: https://github.com/Wildhoney/Redecorate~

**Comment by markerikson** [comment]
Awesome, thanks!

I'll try to generate an additional list of libs based on my current bookmarks queue over the weekend.

**Comment by markerikson** [comment]
Side question: do you have a Twitter account? I'd like to acknowledge the help you're giving here.

**Comment by nmay231** [comment]
No, I don't actually. I'm not really on any social media, except YouTube if that counts (?)

Thanks for the consideration, though :smile:
